"""AI 法律风险合规扫描示例

展示如何使用 legal 规则包扫描 AI 生成内容中的法律风险。
覆盖 14 条 LEGAL 规则，包括：
- AI 免责声明违规（LEGAL-001/002）
- 版权归属问题（LEGAL-003/005）
- 许可证传染风险（LEGAL-004）
- 硬性保证声明（LEGAL-006）
- 个人信息保护法合规（LEGAL-008/009）
- 数据安全法合规（LEGAL-010）
- 生成式AI标注义务（LEGAL-013）
- Deepfake 刑法风险（LEGAL-014）

运行方式：
    cd harness-cook/packages/core
    PYTHONPATH=. python3 ../../examples/legal-risk-scan/demo_legal_scan.py
"""

import sys
import os

# 添加 core 包到 PYTHONPATH
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(script_dir)
core_path = os.path.join(project_root, "packages", "core")
if core_path not in sys.path:
    sys.path.insert(0, core_path)

from harness.compliance import ComplianceEngine, ComplianceCategory
from harness.rule_packs import get_legal_pack
from harness.types import Artifact, ComplianceResult
from harness.bus import EventBus


# ═══════════════════════════════════════════════════════════
#  示例代码片段——包含各类 AI 法律风险
# ═══════════════════════════════════════════════════════════

SAMPLES = {
    "ai_disclaimer_with_warranty": {
        "path": "disclaimer_with_warranty.py",
        "content": """# This file was AI-generated by GPT-4.
# We guarantee correctness and certify completeness.
# All users can rely on this without verification.

def calculate_risk():
    return 0
""",
        "desc": "AI 免责声明包含保证语言（LEGAL-002）",
    },
    "copyright_ai_model": {
        "path": "copyright_ai.ts",
        "content": """/* Copyright: GPT-4 */
// 本代码版权归大模型所有

function processData(data: any) {
    return data;
}
""",
        "desc": "版权归属 AI 模型（LEGAL-003）",
    },
    "gpl_import_chain": {
        "path": "gpl_import.py",
        "content": """from agpl_module import core_handler
# This module is AGPL-3 licensed

def handle_request():
    return core_handler.process()
""",
        "desc": "GPL 许可证 import 链（LEGAL-004）",
    },
    "hard_guarantee_cn": {
        "path": "cn_guarantee.py",
        "content": """# 本公司保证100%安全处理用户数据
# 我们担保所有操作经过合规审核

def process_user_data(data):
    return data
""",
        "desc": "中文硬性保证声明（LEGAL-006）",
    },
    "personal_data_ai": {
        "path": "pii_ai.py",
        "content": """# 个人信息由大模型进行分析处理
# 用户隐私数据通过AI模型自动审核

def analyze_user(data):
    return ai_model.analyze(data)
""",
        "desc": "个人数据交给 AI 处理（LEGAL-008）",
    },
    "critical_data_external": {
        "path": "critical_data.py",
        "content": """# 重要数据通过第三方AI API处理
# 关键数据由外部大模型审核

def export_critical_data(data):
    return external_api.process(data)
""",
        "desc": "重要数据交给外部 AI（LEGAL-010）",
    },
    "deepfake_gen": {
        "path": "deepfake.py",
        "content": """# deepfake 生成模型：冒充他人面部
# 本模块用于 deepfake 生成和仿冒他人

class DeepfakeGenerator:
    def generate(self, target_image):
        return fake_image
""",
        "desc": "Deepfake 生成能力（LEGAL-014）",
    },
    "clean_code": {
        "path": "utils.py",
        "content": """# Regular utility module
# Copyright: Acme Corp 2024

def add(a, b):
    return a + b

def multiply(a, b):
    return a * b
""",
        "desc": "干净代码（不应触发法律规则）",
    },
}


# ═══════════════════════════════════════════════════════════
#  扫描 + 结果解读
# ═══════════════════════════════════════════════════════════

def run_legal_scan():
    """运行 AI 法律风险扫描示例"""
    print("=" * 60)
    print("  AI 法律风险合规扫描示例")
    print("=" * 60)

    # 1. 初始化引擎并加载 legal 规则包
    engine = ComplianceEngine(bus=EventBus())
    engine.load_pack(get_legal_pack())

    stats = engine.stats()
    print(f"\n📊 规则包统计:")
    print(f"   已加载包: {stats['loaded_packs']}")
    print(f"   总规则数: {stats['total_rules']}")

    # 2. 构建产出物列表
    artifacts = [
        Artifact(type="code", path=sample["path"], content=sample["content"])
        for sample in SAMPLES.values()
    ]

    # 3. 逐文件扫描并展示
    print(f"\n🔍 扫描 {len(artifacts)} 个文件...")
    print("\n" + "=" * 60)
    print("  扫描结果")
    print("=" * 60)

    total_violations = 0
    total_passed = 0

    for name, sample in SAMPLES.items():
        single_artifact = Artifact(
            type="code",
            path=sample["path"],
            content=sample["content"],
        )
        results = engine.scan([single_artifact])
        file_violations = [r for r in results if not r.passed]
        file_passed = [r for r in results if r.passed]
        total_violations += len(file_violations)
        total_passed += len(file_passed)

        print(f"\n{'─' * 50}")
        print(f"📄 {sample['path']} — {sample['desc']}")

        if file_violations:
            for v in file_violations:
                severity_icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}
                icon = severity_icon.get(v.severity, "⚪")
                print(f"   {icon} {v.rule_id} ({v.severity})")
                print(f"      发现: {v.findings}")
                print(f"      修复: {v.remediation}")
        else:
            print(f"   ✅ 未触发任何法律规则")

    print(f"\n📊 总计: 通过 {total_passed} 条, 违规 {total_violations} 条")

    # 6. 合规建议
    print("\n" + "=" * 60)
    print("  合规建议")
    print("=" * 60)

    # 重新扫描所有文件收集完整违规
    all_artifacts = [
        Artifact(type="code", path=s["path"], content=s["content"])
        for s in SAMPLES.values()
    ]
    all_results = engine.scan(all_artifacts)
    all_violations = [r for r in all_results if not r.passed]

    critical_violations = [v for v in all_violations if v.severity == "critical"]
    high_violations = [v for v in all_violations if v.severity == "high"]

    if critical_violations:
        print(f"\n🔴 {len(critical_violations)} 个 CRITICAL 级违规 — 必须立即修复:")
        for v in critical_violations:
            print(f"   - {v.rule_id}: {v.findings}")

    if high_violations:
        print(f"\n🟠 {len(high_violations)} 个 HIGH 级违规 — 应在发布前修复:")
        for v in high_violations:
            print(f"   - {v.rule_id}: {v.findings}")

    # 7. 门禁建议
    print("\n" + "=" * 60)
    print("  门禁建议")
    print("=" * 60)

    if critical_violations:
        print("建议使用 STRICT 门禁模式 — critical 级违规阻断执行")
    elif high_violations:
        print("建议使用 HYBRID 门禁模式 — critical+high 级违规阻断，其余仅记录")
    else:
        print("建议使用 LOOSE 门禁模式 — 所有违规仅记录，不阻断")

    return all_violations


# ═══════════════════════════════════════════════════════════
#  快速扫描 API
# ═══════════════════════════════════════════════════════════

def quick_scan_demo():
    """展示 scan_quick 快速扫描 API"""
    print("\n" + "=" * 60)
    print("  快速扫描 API（scan_quick）")
    print("=" * 60)

    engine = ComplianceEngine(bus=EventBus())
    engine.load_pack(get_legal_pack())

    # 单行代码快速扫描
    code = "# 本公司保证100%安全处理"
    results = engine.scan_quick(code, "inline_check.py")

    violations = [r for r in results if not r.passed]
    print(f"\n扫描内容: {code}")
    print(f"违规数: {len(violations)}")
    for v in violations:
        print(f"   {v.rule_id}: {v.findings}")


if __name__ == "__main__":
    violations = run_legal_scan()
    quick_scan_demo()

    print(f"\n{'=' * 60}")
    print("  总结")
    print("=" * 60)
    print(f"共发现 {len(violations)} 个 AI 法律风险违规点")
    print("建议在项目 CI 流程中集成 legal 规则包扫描")
    print("=" * 60)
