"""AI Legal Risk Compliance Rule Pack

Scans for legal risks associated with AI-generated content:
copyright violations, missing disclaimers, liability exposure,
license conflicts, and regulatory compliance gaps.

All rule IDs use the LEGAL-xxx prefix and fall under ComplianceCategory.LEGAL.

Legal risk dimensions covered:
  1. AI-generated content disclaimer — 文件缺少 AI 生成标记/免责声明
  2. Copyright/license conflict — AI 生成代码与已知开源许可证冲突
  3. Liability exposure — 代码中包含可能构成法律责任的声明/承诺
  4. Regulatory compliance — GDPR/中国数据安全法/网络安全法相关条目
  5. Intellectual property — 商标/专利/著作权相关风险标记
"""

from __future__ import annotations

from harness.compliance import ComplianceRule, ComplianceCategory, RulePack


def get_legal_pack() -> RulePack:
    """Return the AI legal risk compliance rule pack."""

    rules = [
        # ─── AI 生成内容免责声明 ──────────────────────────────

        ComplianceRule(
            id="LEGAL-001",
            category=ComplianceCategory.LEGAL,
            pattern=r"^.{0,50}$",
            severity="medium",
            description="AI-generated file lacks disclaimer — files shorter than typical hand-written code may be AI-generated without legal notice",
            remediation="Add AI-generated content disclaimer: '// This file was generated by an AI tool. Review carefully before use.' or equivalent comment in the file header",
            auto_fixable=True,
            matcher_type="regex",
            matcher_config={
                # 仅对没有 AI disclaimer 标记的文件触发
                # 与 LEGAL-002 互补：LEGAL-002 检测"有声明但措辞不当"，LEGAL-001 检测"无声明"
                "negative_pattern": r"(?:AI[-\s]?generated|auto[-\s]?generated|machine[-\s]?generated|generated[-\s]?by[-\s]?AI|AI[-\s]?assisted)",
                "min_line_count": 5,  # 仅对有实质内容的文件检查
            },
        ),

        ComplianceRule(
            id="LEGAL-002",
            category=ComplianceCategory.LEGAL,
            # 排除否定语境: "No warranty", "without guarantee", "不保证", "无担保"
            # 正则逻辑: 在 AI 上下文附近，如果保证性词语前面 0-30 字符内没有否定词，则触发
            pattern=r"(?:AI[-\s]?generated|auto[-\s]?generated|machine[-\s]?generated|generated[-\s]?by[-\s]?AI|AI[-\s]?assisted).{0,30}(?:we\s+guarantee|we\s+warrant|we\s+certify|guaranteed\s+to|warranted\s+to|certified\s+as|我们保证|我们担保|我们承诺|本公司保证|本公司担保|本公司承诺)",
            severity="critical",
            description="AI disclaimer contains affirmative warranty/guarantee language — creates false legal commitment",
            remediation="Replace warranty language with caveat: 'This file was AI-generated. No warranty of correctness, completeness, or fitness for purpose is provided. Human review is required before production use.'",
            auto_fixable=True,
        ),

        # ─── 版权与许可证冲突 ────────────────────────────────

        ComplianceRule(
            id="LEGAL-003",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:Copyright|©|著作权|版权)\s*[:=]\s*(?:AI|GPT|Claude|OpenAI|Anthropic|ChatGPT|Copilot|大模型|人工智能)",
            severity="high",
            description="Copyright attribution to AI model — AI cannot hold copyright under most jurisdictions",
            remediation="Attribute copyright to the human author/organization, not the AI tool. Use 'Generated with [tool], copyright [organization]' format",
        ),

        ComplianceRule(
            id="LEGAL-004",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:GPL|AGPL|GPL[-\s]?3|GPL[-\s]?2|Affero)[^;\n]{0,100}(?:import|from|require|include|reference)",
            severity="high",
            description="GPL/AGPL license referenced in import chain — copyleft contamination risk for proprietary code",
            remediation="Verify the actual license of the imported dependency. If GPL/AGPL, evaluate whether your project can comply with copyleft obligations, or find an alternative with a permissive license (MIT/Apache/BSD)",
            languages=["python", "javascript", "typescript", "go", "java"],
        ),

        ComplianceRule(
            id="LEGAL-005",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:MIT|Apache|BSD|ISC|LGPL)[^;\n]{0,100}(?:Copyright|©|license|许可|授权)[^;\n]{0,200}(?:modify|修改|removed|删除|stripped|altered|changed)",
            severity="high",
            description="Permissive license copyright/attribution appears to be modified or removed — license violation",
            remediation="Permissive licenses (MIT/Apache/BSD) require retaining the original copyright notice and license text. Restore the original attribution or verify the modification is permitted by the specific license terms",
        ),

        # ─── 法律责任暴露 ────────────────────────────────────

        ComplianceRule(
            id="LEGAL-006",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:we\s+guarantee|we\s+warrant|we\s+certify|we\s+ensure|we\s+promise|本公司保证|本公司担保|本公司承诺|我们保证|我们承诺|我方保证|100%\s*(?:safe|secure|correct|accurate|reliable|安全|正确|准确|可靠))",
            severity="critical",
            description="Hard guarantee/warranty statement in code comments or docs — creates potential legal liability",
            remediation="Replace absolute guarantees with qualified statements: 'Designed to... / Intended to... / Best effort to...' — avoid language that could constitute a legal warranty",
        ),

        ComplianceRule(
            id="LEGAL-007",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?: indemnify|indemnification|hold\s+harmless|免责|赔偿|indemnity|shall\s+not\s+be\s+liable|不承担|不负)(?:.{0,100}AI|.{0,100}auto[-\s]?generated|.{0,100}machine)",
            severity="high",
            description="Indemnification/liability clause referencing AI-generated content — legal exposure needs legal counsel review",
            remediation="Have legal counsel review any indemnification or liability clauses that reference AI-generated content. Standard software liability disclaimers may not adequately cover AI-specific risks",
        ),

        # ─── 数据安全法规合规 ────────────────────────────────

        ComplianceRule(
            id="LEGAL-008",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:个人信息|personal\s+data|user\s+data|客户数据|用户隐私|personal\s+information)(?:.{0,200})(?:AI|大模型|LLM|GPT|Claude|machine\s+learning|model|chatbot|智能|智能客服|智能助手)",
            severity="high",
            description="Personal data processed by AI/LLM — GDPR/中国个人信息保护法合规 gap",
            remediation="Ensure: (1) data minimization — only necessary data sent to AI; (2) consent obtained; (3) AI processing disclosed to users; (4) data not retained by AI provider; (5) DPIA completed for high-risk processing",
        ),

        ComplianceRule(
            id="LEGAL-009",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:GDPR|个人信息保护法|数据安全法|网络安全法|PIPL|CSL|DSL|数据出境|cross[-\s]?border\s+data|data\s+transfer|数据跨境)(?:.{0,300})(?:without|未|no|lack|缺少|缺失|absent)(?:.{0,100})(?:consent|同意|授权|approval|assessment|评估|审查)",
            severity="critical",
            description="Data protection regulation referenced without required consent/assessment — legal compliance violation",
            remediation="Before processing personal data: obtain explicit consent (GDPR Art.6/PIPL Art.13), complete security assessment (CSL/DSL), and for cross-border transfers, obtain certification or pass standard contract (PIPL Art.38)",
        ),

        ComplianceRule(
            id="LEGAL-010",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:重要数据|critical\s+data|核心数据|core\s+data|国家秘密|state\s+secret|national\s+secret)(?:.{0,200})(?:AI|大模型|LLM|cloud|云端|external|第三方|third[-\s]?party|API)",
            severity="critical",
            description="Critical/important data referenced for AI or cloud processing — 中国数据安全法/网络安全法 严禁未经评估的外部处理",
            remediation="重要数据和核心数据严禁未经主管部门安全评估即交给外部 AI/云处理。必须: (1) 数据分类分级; (2) 安全风险评估; (3) 主管部门审批; (4) 本地化处理优先",
        ),

        # ─── 知识产权风险 ────────────────────────────────────

        ComplianceRule(
            id="LEGAL-011",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:patent|专利|trademark|商标|trade\s+secret|商业秘密|proprietary|专有|独占|exclusive)(?:.{0,200})(?:AI|auto|generate|生成|output|产出|model)",
            severity="high",
            description="IP-protected content (patent/trademark/trade secret) referenced in AI generation context — IP contamination risk",
            remediation="AI-generated content may inadvertently reproduce protected IP. Ensure: (1) no trade secrets in AI prompts; (2) patent-clearance review for AI-generated code; (3) trademark usage guidelines followed; (4) NDA compliance when using proprietary data as AI input",
        ),

        ComplianceRule(
            id="LEGAL-012",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:抄袭|plagiarism|copy|verbatim|照搬|直接复制|照抄)(?:.{0,100})(?:code|代码|source|源码|implementation|实现|solution|方案)",
            severity="high",
            description="Code plagiarism/copying language detected — copyright infringement risk",
            remediation="AI-generated code must be reviewed for originality. Avoid verbatim reproduction of existing code. When referencing external sources, attribute properly and ensure license compatibility. Use AI output as inspiration, not direct copy",
        ),

        # ─── AI 特定法规合规 ──────────────────────────────────

        ComplianceRule(
            id="LEGAL-013",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:生成式人工智能|Generative\s+AI|AIGC|深度合成|Deep\s+Synthesis|深度合成服务|合成服务|AI生成内容|AI[-\s]?generated\s+content)(?:.{0,300})(?:without|未|no|lack|缺少|缺失)(?:.{0,100})(?:label|标识|标记|tag|watermark|水印|disclosure|披露|声明|notice)",
            severity="high",
            description="Generative AI content without required labeling/watermark — 中国《生成式人工智能服务管理暂行办法》/《互联网信息服务算法推荐管理规定》合规 gap",
            remediation="中国法规要求: (1) 生成式AI内容必须标注'AI生成'; (2) 深度合成内容必须添加水印/标识; (3) 不得利用AI生成虚假信息; (4) 对使用者进行显著提示",
        ),

        ComplianceRule(
            id="LEGAL-014",
            category=ComplianceCategory.LEGAL,
            pattern=r"(?:deepfake|虚假|fake|伪造|forgery|impersonation|冒充|冒名|虚假信息|misinformation|disinformation|谣言|rumor)(?:.{0,200})(?:generate|生成|create|制作|produce|produce|合成|compose|AI|model|大模型|LLM)",
            severity="critical",
            description="Deepfake/fake content generation capability detected — 严重法律风险（中国刑法/治安管理处罚法/《深度合成管理规定》）",
            remediation="禁止开发/提供 deepfake 工具用于冒充他人。技术必须: (1) 添加不可删除的标识/水印; (2) 用户实名认证; (3) 留存日志; (4) 仅限合法用途; (5) 不提供未标识的生成内容",
        ),
    ]

    return RulePack("legal", ComplianceCategory.LEGAL, rules)
